'use client';
import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react';
import {Building2,History,KeyRound,RefreshCcw,Settings,ShieldCheck,UserPlus,Users} from 'lucide-react';
import {getAdmin,inviteMember,revokeInvitation,saveRole,updateMember,updateOrganization,updateSettings,type AdminData,type Member} from '@/services/organization-admin';
import {PermissionGuard} from '@/components/permissions/permission-guard';
const input='h-9 w-full rounded-[5px] border border-[#d8d9dc] bg-white px-3 text-[13px] outline-none focus:border-[#635bff]';
const button='h-9 rounded-[5px] border border-[#d8d9dc] bg-white px-3 text-[13px] font-medium';
const primary='h-9 rounded-[5px] bg-[#635bff] px-4 text-[13px] font-semibold text-white';
const tabs=[['organization','Organisation',Building2],['team','Équipe',Users],['roles','Rôles',KeyRound],['preferences','Paramètres',Settings],['security','Sécurité',ShieldCheck],['audit','Audit',History]] as const;
function val(f:FormData,k:string){return String(f.get(k)||'').trim()||null}
export function OrganizationAdminPage(){
 const [data,setData]=useState<AdminData|null>(null),[tab,setTab]=useState<(typeof tabs)[number][0]>('organization'),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{try{setError('');setData(await getAdmin())}catch{setError("Le centre d’administration est indisponible.")}},[]);useEffect(()=>{load()},[load]);
 async function run(action:()=>Promise<unknown>,message:string){try{setError('');await action();setNotice(message);await load()}catch(e){const detail=(e as {response?:{data?:{detail?:string}}})?.response?.data?.detail;setError(detail==='organization_requires_an_active_owner'?"Une organisation doit toujours conserver au moins un propriétaire actif.":detail||"L’opération n’a pas abouti.")}}
 if(!data)return <div className="p-6 text-[13px]">{error||'Chargement de l’administration…'}</div>;
 return <div className="min-h-full bg-[#f7f7f6]"><header className="border-b bg-white px-6 py-5"><div className="flex items-end justify-between"><div><p className="text-[12px] text-[#69707d]">Administration › Espace de travail</p><h1 className="text-[24px] font-semibold tracking-[-.02em]">Organisation et équipe</h1><p className="text-[13px] text-[#69707d]">Identité, collaborateurs, accès et règles communes de l’agence.</p></div><button className={button} onClick={load}><RefreshCcw className="mr-2 inline" size={14}/>Actualiser</button></div></header>
 <nav className="flex gap-1 overflow-x-auto border-b bg-white px-5">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex h-12 items-center gap-2 border-b-2 px-3 text-[13px] ${tab===id?'border-[#635bff] font-semibold text-[#29266f]':'border-transparent text-[#606773]'}`}><Icon size={15}/>{label}</button>)}</nav>
 <main className="mx-auto max-w-[1280px] p-5">{notice&&<div className="mb-3 rounded-[5px] bg-emerald-50 px-4 py-3 text-[13px] text-emerald-800">{notice}</div>}{error&&<div className="mb-3 rounded-[5px] bg-red-50 px-4 py-3 text-[13px] text-red-700">{error}</div>}
 {tab==='organization'&&<Organization data={data} run={run}/>} {tab==='team'&&<Team data={data} run={run}/>} {tab==='roles'&&<Roles data={data} run={run}/>} {tab==='preferences'&&<Preferences data={data} run={run}/>} {tab==='security'&&<Security data={data} run={run}/>} {tab==='audit'&&<Audit data={data}/>}</main></div>
}
function Card({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="rounded-[7px] bg-white shadow-[0_1px_2px_rgba(0,0,0,.08)]"><div className="border-b px-5 py-4"><h2 className="text-[15px] font-semibold">{title}</h2><p className="text-[12px] text-[#69707d]">{description}</p></div><div className="p-5">{children}</div></section>}
function Organization({data,run}:{data:AdminData;run:(a:()=>Promise<unknown>,m:string)=>void}){const o=data.organization;async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);run(()=>updateOrganization({expected_version:o.row_version,organization_name:val(f,'name'),legal_name:val(f,'legal'),country:val(f,'country'),city:val(f,'city'),address:val(f,'address'),phone:val(f,'phone'),email:val(f,'email'),website:val(f,'website'),registration_number:val(f,'registration'),tax_number:val(f,'tax')}),'Profil de l’agence mis à jour.')}return <Card title="Profil de l’agence" description="Informations officielles réutilisées dans les factures, documents et communications."><PermissionGuard permission="organization.manage" fallback={<ReadOnly/>}><form onSubmit={submit} className="grid gap-4 md:grid-cols-2">{[['name','Nom commercial','organization_name'],['legal','Raison sociale','legal_name'],['registration','Numéro d’enregistrement','registration_number'],['tax','Identifiant fiscal','tax_number'],['country','Pays','country'],['city','Ville','city'],['phone','Téléphone','phone'],['email','Email','email'],['website','Site web','website'],['address','Adresse','address']].map(([n,l,k])=><label key={n} className="text-[12px] text-[#555d68]">{l}<input className={`${input} mt-1`} name={n} defaultValue={String(o[k]||'')}/></label>)}<div className="md:col-span-2"><button className={primary}>Enregistrer le profil</button></div></form></PermissionGuard></Card>}
function Team({data,run}:{data:AdminData;run:(a:()=>Promise<unknown>,m:string)=>void}){async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);run(()=>inviteMember(String(f.get('email')),String(f.get('role'))),'Invitation envoyée.')}return <div className="grid gap-4"><Card title="Inviter un collaborateur" description="L’invitation est envoyée par Clerk et expire automatiquement."><PermissionGuard permission="team.write"><form onSubmit={invite} className="flex flex-wrap gap-2"><input required type="email" name="email" className={`${input} max-w-sm`} placeholder="collaborateur@agence.com"/><select name="role" className={`${input} max-w-[220px]`}>{data.roles.map(r=><option key={r.id} value={r.role_code}>{r.role_name}</option>)}</select><button className={primary}><UserPlus className="mr-2 inline" size={14}/>Inviter</button></form></PermissionGuard></Card><Card title={`Membres (${data.members.length})`} description="Suspendre un accès prend effet côté API sans supprimer l’historique."><div className="divide-y">{data.members.map(m=><MemberRow key={m.id} member={m} roles={data.roles} run={run}/>)}</div></Card>{data.invitations.length>0&&<Card title="Invitations" description="Invitations en attente, acceptées ou révoquées."><div className="divide-y">{data.invitations.map(x=><div className="flex items-center justify-between py-3 text-[13px]" key={String(x.id)}><div><b>{String(x.email)}</b><p className="text-[12px] text-[#69707d]">{String(x.role_code)} · {String(x.status)}</p></div>{x.status==='PENDING'&&<PermissionGuard permission="team.manage"><button className={button} onClick={()=>run(()=>revokeInvitation(String(x.id)),'Invitation révoquée.')}>Révoquer</button></PermissionGuard>}</div>)}</div></Card>}</div>}
function MemberRow({member,roles,run}:{member:Member;roles:AdminData['roles'];run:(a:()=>Promise<unknown>,m:string)=>void}){const [role,setRole]=useState(member.role_code),[status,setStatus]=useState(member.status);return <div className="flex flex-wrap items-center justify-between gap-3 py-3 text-[13px]"><div><b>{member.member_display_name||member.member_email||'Membre'}</b><p className="text-[12px] text-[#69707d]">{member.member_email||member.id}</p></div><PermissionGuard permission="team.manage" fallback={<span>{member.role_name} · {member.status}</span>}><div className="flex gap-2"><select className={input} value={role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option key={r.id} value={r.role_code}>{r.role_name}</option>)}</select><select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="ACTIVE">Actif</option><option value="SUSPENDED">Suspendu</option></select><button className={button} onClick={()=>run(()=>updateMember(member.id,{role_code:role,status,expected_version:member.row_version}),'Accès du membre mis à jour.')}>Appliquer</button></div></PermissionGuard></div>}
function Roles({data,run}:{data:AdminData;run:(a:()=>Promise<unknown>,m:string)=>void}){const groups=useMemo(()=>data.permissions.reduce<Record<string,AdminData['permissions']>>((all,p)=>{const key=p.permission_code.split('.')[0]||'other';(all[key]??=[]).push(p);return all},{}),[data.permissions]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);run(()=>saveRole({code:String(f.get('code')).toUpperCase(),name:f.get('name'),description:f.get('description'),permissions:f.getAll('permissions')}),'Rôle enregistré.')}return <div className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><Card title="Rôles existants" description="Les rôles système forment le socle; les rôles personnalisés répondent à votre organisation.">{data.roles.map(r=><div className="border-b py-3 text-[13px]" key={r.id}><b>{r.role_name}</b><p className="text-[12px] text-[#69707d]">{r.permission_count} droits · {r.member_count} membres {r.system_role?'· Système':''}</p></div>)}</Card><Card title="Nouveau rôle personnalisé" description="Accordez uniquement les capacités nécessaires."><PermissionGuard permission="roles.manage" fallback={<ReadOnly/>}><form onSubmit={submit} className="grid gap-3"><div className="grid grid-cols-2 gap-2"><input required name="code" className={input} placeholder="SUPERVISEUR_PAYS"/><input required name="name" className={input} placeholder="Superviseur pays"/></div><input name="description" className={input} placeholder="Description"/><div className="max-h-[400px] overflow-y-auto rounded-[5px] border p-3">{Object.entries(groups).map(([group,permissions])=><div key={group} className="mb-4"><b className="text-[12px] uppercase text-[#69707d]">{group}</b><div className="mt-2 grid gap-2 sm:grid-cols-2">{permissions.map(p=><label className="flex gap-2 text-[12px]" key={p.id}><input type="checkbox" name="permissions" value={p.permission_code}/><span><b>{p.permission_code}</b><small className="block text-[#69707d]">{p.description}</small></span></label>)}</div></div>)}</div><button className={primary}>Créer le rôle</button></form></PermissionGuard></Card></div>}
function Preferences({data,run}:{data:AdminData;run:(a:()=>Promise<unknown>,m:string)=>void}){const s=data.settings||{row_version:1};async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);run(()=>updateSettings({expected_version:s.row_version,timezone:val(f,'timezone'),currency_code:val(f,'currency'),country_code:val(f,'country'),language_code:val(f,'language'),date_format:val(f,'date'),weight_unit:val(f,'weight'),volume_unit:val(f,'volume'),notification_email:val(f,'email'),settings:s.settings||{},security:s.security||{}}),'Préférences enregistrées.')}return <Card title="Préférences de l’espace" description="Formats appliqués à tous les collaborateurs de l’agence."><PermissionGuard permission="settings.write" fallback={<ReadOnly/>}><form onSubmit={submit} className="grid gap-4 md:grid-cols-2">{[['timezone','Fuseau horaire','timezone'],['currency','Devise','currency_code'],['country','Code pays','country_code'],['language','Langue','language_code'],['date','Format de date','date_format'],['weight','Unité de poids','weight_unit'],['volume','Unité de volume','volume_unit'],['email','Email notifications','notification_email']].map(([n,l,k])=><label className="text-[12px]" key={n}>{l}<input name={n} className={`${input} mt-1`} defaultValue={String(s[k]||'')}/></label>)}<button className={primary}>Enregistrer</button></form></PermissionGuard></Card>}
function Security({data,run}:{data:AdminData;run:(a:()=>Promise<unknown>,m:string)=>void}){const s=data.settings||{row_version:1},sec=(s.security||{}) as Record<string,unknown>;async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);run(()=>updateSettings({...s,expected_version:s.row_version,security:{require_mfa:f.get('mfa')==='on',session_timeout_minutes:Number(f.get('timeout'))}}),'Politique de sécurité mise à jour.')}return <Card title="Politique de sécurité" description="Ces règles complètent l’authentification Clerk et le contrôle RBAC des API."><PermissionGuard permission="security.manage" fallback={<ReadOnly/>}><form onSubmit={submit} className="grid max-w-xl gap-4"><label className="flex items-center gap-3 text-[13px]"><input name="mfa" type="checkbox" defaultChecked={Boolean(sec.require_mfa)}/>Exiger l’authentification multifacteur pour l’agence</label><label className="text-[12px]">Expiration de session (minutes)<input name="timeout" type="number" min="15" max="10080" className={`${input} mt-1`} defaultValue={Number(sec.session_timeout_minutes||480)}/></label><p className="rounded-[5px] bg-amber-50 p-3 text-[12px] text-amber-900">L’application de la MFA au niveau de la connexion nécessite aussi son activation dans Clerk Dashboard.</p><button className={primary}>Enregistrer la politique</button></form></PermissionGuard></Card>}
function Audit({data}:{data:AdminData}){return <Card title="Journal d’audit" description="Dernières mutations administratives de l’organisation."><div className="overflow-x-auto"><table className="w-full text-left text-[12px]"><thead><tr className="border-b text-[#69707d]"><th className="py-2">Date</th><th>Action</th><th>Objet</th><th>Acteur</th></tr></thead><tbody>{data.audit.map(x=><tr className="border-b" key={String(x.id)}><td className="py-3">{new Date(String(x.created_at)).toLocaleString('fr-FR')}</td><td>{String(x.action)}</td><td>{String(x.entity_type)} · {String(x.entity_id)}</td><td>{String(x.actor_name||x.actor_id||'Système')}</td></tr>)}</tbody></table>{!data.audit.length&&<p className="py-8 text-center text-[#69707d]">Aucune mutation administrative enregistrée.</p>}</div></Card>}
function ReadOnly(){return <p className="rounded-[5px] bg-[#f2f2f1] p-3 text-[12px] text-[#69707d]">Consultation seule : votre rôle ne permet pas cette modification.</p>}
