const businessLabels: Record<string, string> = {
  DOCUMENT_MISSING: "Document manquant",
  PAYMENT_DUE: "Paiement à régulariser",
  QUOTE_FOLLOWUP: "Devis sans réponse",
  PACKAGE_DROP_REMINDER: "Colis à déposer",
  PICKUP_REMINDER: "Retrait à effectuer",
  CLIENT_INACTIVE: "Client inactif",
  DUE: "À effectuer",
  SCHEDULED: "Programmée",
  QUEUED: "En file d’attente",
  SENDING: "En cours d’envoi",
  SENT: "Envoyée",
  DELIVERED: "Délivrée",
  READ: "Lue",
  WAITING_RESPONSE: "En attente de réponse",
  RESPONDED: "Réponse reçue",
  FAILED: "Échec",
  ESCALATED: "Transmise à un responsable",
  PAUSED: "En pause",
  COMPLETED: "Terminée",
  CANCELLED: "Annulée",
  DRAFT: "Brouillon",
  OPEN: "Ouvert",
  PREPARING: "En préparation",
  NEAR_CAPACITY: "Presque plein",
  FULL: "Complet",
  PENDING_VALIDATION: "À valider",
  READY_FOR_SHIPMENT: "Prêt à expédier",
  READY_FOR_BATCH: "Prêt au groupage",
  READY_FOR_DISPATCH: "Prêt au départ",
  READY_FOR_PICKUP: "Prêt au retrait",
  CONVERTED_TO_SHIPMENT: "Converti en expédition",
  BLOCKED: "Bloqué",
  ARCHIVED: "Archivé",
  ACTIVE: "Actif",
  INACTIVE: "Inactif",
  LIMITED: "Capacité limitée",
  SUSPENDED: "Suspendu",
  MAINTENANCE: "En maintenance",
  APPROVED: "Approuvé",
  REJECTED: "Rejeté",
  EXPIRED: "Expiré",
  PUBLISHED: "Publié",
  NEEDS_REVIEW: "À vérifier",
  CONFIRMED: "Confirmé",
  RECEIVED: "Reçu",
  RECEIVED_AT_ORIGIN: "Reçu à l’origine",
  WAREHOUSED: "En entrepôt",
  WAREHOUSE_PROCESSING: "En traitement à l’entrepôt",
  BATCHED: "Groupé",
  SHIPPED: "Expédié",
  IN_TRANSIT: "En transit",
  ARRIVED: "Arrivé",
  ARRIVED_DESTINATION: "Arrivé à destination",
  CLEARED: "Dédouané",
  RETURNED: "Retourné",
  PLANNED: "Planifié",
  DELAYED: "En retard",
  DEPARTED: "Parti",
  CHECKED_IN: "Client accueilli",
  VERIFIED: "Vérifié",
  RELEASED: "Remis au client",
  PAID: "Payé",
  UNPAID: "Non payé",
  PARTIALLY_PAID: "Partiellement payé",
  PASSED: "Validé",
  WARNING: "À vérifier",
  PENDING: "En attente",
  MISSING: "Manquant",
  WHATSAPP: "WhatsApp",
  EMAIL: "E-mail",
  IN_APP: "Tâche interne",
  PHONE: "Appel manuel",
  LOW: "Faible",
  NORMAL: "Normale",
  HIGH: "Haute",
  URGENT: "Urgente",
  CLIENT: "Client",
  DOSSIER: "Dossier",
  PACKAGE: "Colis",
  INVOICE: "Facture",
  PAYMENT: "Paiement",
  QUOTE: "Devis",
  PICKUP: "Retrait",
  CREATED: "Créé",
  UPDATED: "Mis à jour",
  DEPARTURE: "Départ",
  ARRIVAL: "Arrivée",
  LOADING: "Chargement",
  UNLOADING: "Déchargement",
  CUSTOMS: "Douane",
  CONTROL: "Contrôle",
  INCIDENT: "Incident",
  DELIVERY: "Livraison",
  ETA_UPDATE: "Mise à jour de l’arrivée estimée",
};

export function businessLabel(value: unknown, fallback = "Non renseigné") {
  if (value === null || value === undefined || value === "") return fallback;
  const raw = String(value).trim();
  const key = raw.toUpperCase();
  if (businessLabels[key]) return businessLabels[key];

  // Last-resort presentation for configurable agency values. API codes must
  // never be shown as raw SCREAMING_SNAKE_CASE in an operational screen.
  return raw
    .replaceAll("_", " ")
    .toLocaleLowerCase("fr-FR")
    .replace(/^./, (letter) => letter.toLocaleUpperCase("fr-FR"));
}
