"use client";
import axios from "axios";
import {Bell,Download,Map,RefreshCcw,Search,Timer} from "lucide-react";
import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {OperationPageHeader} from "@/components/ui/operation-page-header";
import {createTrackingAlert,exportTracking,getGlobalTrackingTimeline,getTrackingStats,listTracking,type TrackingEvent,type TrackingItem,type TrackingStats} from "@/services/tracking";

const button="inline-flex h-9 items-center gap-2 rounded-md border border-[#cfd5dd] bg-white px-3 text-[13px] font-medium shadow-sm hover:bg-[#f7f8fa]";
const input="h-9 rounded-md border border-[#cfd5dd] bg-white px-3 text-[13px] outline-none focus:border-[#2f7df6]";
const emptyStats:TrackingStats={packages_in_transit:0,active_shipments:0,delivered_today:0,delays:0,incidents_open:0,average_transit_hours:null};
export function TrackingPage(){
 const [items,setItems]=useState<TrackingItem[]>([]),[events,setEvents]=useState<TrackingEvent[]>([]),[stats,setStats]=useState(emptyStats);const [q,setQ]=useState(""),[status,setStatus]=useState(""),[risk,setRisk]=useState(""),[country,setCountry]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[alertFor,setAlertFor]=useState<TrackingItem|null>(null);const [page,setPage]=useState(1),[pages,setPages]=useState(0);
 async function load(next=page){setLoading(true);setError("");try{const [list,kpis,timeline]=await Promise.all([listTracking({q:q||undefined,status:status||undefined,risk_level:risk||undefined,country:country||undefined,page:next}),getTrackingStats(),getGlobalTrackingTimeline()]);setItems(list.items);setPages(list.pagination.total_pages);setPage(next);setStats(kpis);setEvents(timeline)}catch(e){setError(message(e))}finally{setLoading(false)}}
 // The selected filters are the intentional refresh contract.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{const id=setTimeout(()=>load(1),200);return()=>clearTimeout(id)},[q,status,risk,country]);
 const routes=useMemo(()=>items.slice(0,8),[items]);
 async function download(){try{const blob=await exportTracking();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="slaivio-tracking.csv";a.click();URL.revokeObjectURL(url)}catch(e){setError(message(e))}}
 const cards=[['Colis en transit',stats.packages_in_transit],['Expéditions actives',stats.active_shipments],['Livraisons aujourd’hui',stats.delivered_today],['Retards détectés',stats.delays],['Incidents ouverts',stats.incidents_open],['Transit moyen',stats.average_transit_hours==null?'—':`${stats.average_transit_hours} h`]];
 return <div className="min-h-full bg-[#f7f7f6] text-[#1f2328]"><OperationPageHeader title="Tracking" description="Supervisez en temps réel tous les colis, expéditions et mouvements logistiques." actions={<><button onClick={()=>load()} className={button}><RefreshCcw size={15}/>Actualiser</button><button onClick={download} className={button}><Download size={15}/>Exporter</button></>}/>
 <section className="grid gap-3 border-b bg-white p-5 sm:grid-cols-2 xl:grid-cols-6">{cards.map(([label,value])=><article key={String(label)} className="rounded-md border border-[#d8dce2] p-4"><p className="text-[13px] text-[#5f6b76]">{label}</p><p className="mt-3 text-[30px] tracking-[-.04em]">{value}</p></article>)}</section>
 <section className="grid border-b bg-white lg:grid-cols-2"><div className="border-r p-5"><div className="mb-4 flex items-center gap-2 font-semibold"><Map size={17}/>Carte des routes actives</div><div className="relative min-h-[310px] overflow-hidden rounded-lg border bg-[radial-gradient(circle_at_20%_30%,#dbeafe_0,transparent_28%),radial-gradient(circle_at_70%_60%,#dcfce7_0,transparent_30%),#f8fafc] p-5">{routes.map(r=><Link href={`/app/tracking/${r.id}`} key={r.id} className="mb-3 flex items-center gap-3 rounded-md border bg-white/90 p-3 text-[12px] shadow-sm"><span className={`h-3 w-3 rounded-full ${r.is_delayed?'bg-red-500':r.risk_level==='HIGH'||r.risk_level==='CRITICAL'?'bg-orange-500':'bg-emerald-500'}`}/><b>{r.origin_city||r.origin_country||'Origine'}</b><span>→</span><b>{r.destination_city||r.destination_country||'Destination'}</b><span className="ml-auto text-slate-500">{r.last_location||'Position inconnue'}</span></Link>)}</div></div><div className="p-5"><div className="mb-4 flex items-center gap-2 font-semibold"><Timer size={17}/>Timeline globale</div><div className="max-h-[330px] space-y-1 overflow-y-auto">{events.map(e=><Link href={`/app/tracking/${e.expedition_id}`} key={e.id} className="block border-b py-3 text-[13px]"><div className="flex justify-between"><b>{e.tracking_id} · {e.title}</b><time className="text-[11px] text-slate-500">{formatDate(e.occurred_at)}</time></div><p className="mt-1 text-slate-600">{e.location||e.description||e.event_type}</p></Link>)}</div></div></section>
 <section className="bg-white"><div className="flex flex-wrap gap-2 border-b p-4"><label className="flex h-9 min-w-[280px] flex-1 items-center rounded-md border px-3"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher colis, expédition, client…" className="ml-2 flex-1 outline-none"/></label><select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tous les statuts</option><option value="IN_TRANSIT">En transit</option><option value="CUSTOMS_CLEARANCE">Douane</option><option value="DELIVERED">Livré</option><option value="BLOCKED">Bloqué</option></select><select className={input} value={risk} onChange={e=>setRisk(e.target.value)}><option value="">Tous les risques</option><option value="LOW">Normal</option><option value="MEDIUM">Attention</option><option value="HIGH">Élevé</option><option value="CRITICAL">Critique</option></select><input className={input} value={country} onChange={e=>setCountry(e.target.value)} placeholder="Pays"/></div>{error&&<p className="m-4 rounded bg-red-50 p-3 text-red-700">{error}</p>}<div className="overflow-x-auto"><table className="min-w-[1100px] w-full text-left text-[13px]"><thead className="border-b bg-[#f7f8fa] text-[#59636e]"><tr>{['Tracking ID','Type','Origine','Destination','Dernière position','Statut','ETA','Signal','Alertes',''].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={10} className="p-10 text-center">Actualisation…</td></tr>:items.map(r=><tr key={r.id} className="border-b hover:bg-[#fafafa]"><td className="px-4 py-3 font-semibold"><Link href={`/app/tracking/${r.id}`}>{r.tracking_id}</Link></td><td className="px-4 py-3">Expédition</td><td className="px-4 py-3">{r.origin_city||r.origin_country||'—'}</td><td className="px-4 py-3">{r.destination_city||r.destination_country||'—'}</td><td className="px-4 py-3">{r.last_location||'—'}</td><td className="px-4 py-3"><Status item={r}/></td><td className="px-4 py-3">{formatDate(r.eta_at)}</td><td className="px-4 py-3">{freshness(r.last_signal_at)}</td><td className="px-4 py-3">{r.open_alerts}</td><td className="px-4 py-3"><button onClick={()=>setAlertFor(r)} className="rounded p-2 hover:bg-amber-50"><Bell size={15}/></button></td></tr>)}</tbody></table></div><footer className="flex justify-end gap-2 p-4"><button disabled={page<=1} onClick={()=>load(page-1)} className={button}>Précédent</button><span className="px-3 py-2 text-[13px]">{page}/{Math.max(pages,1)}</span><button disabled={page>=pages} onClick={()=>load(page+1)} className={button}>Suivant</button></footer></section>{alertFor&&<AlertModal item={alertFor} onClose={()=>setAlertFor(null)} onDone={()=>{setAlertFor(null);load()}}/>}</div>}
function AlertModal({item,onClose,onDone}:{item:TrackingItem;onClose:()=>void;onDone:()=>void}){const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await createTrackingAlert(item.id,{severity:String(f.get('severity')),title:String(f.get('title')),description:String(f.get('description')||'')});onDone()}catch(x){setError(message(x))}}return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30 p-4"><form onSubmit={submit} className="w-full max-w-md space-y-3 rounded-xl bg-white p-5"><h2 className="font-semibold">Créer une alerte · {item.tracking_id}</h2><select name="severity" className={`${input} w-full`}><option value="MEDIUM">Moyenne</option><option value="HIGH">Élevée</option><option value="CRITICAL">Critique</option><option value="LOW">Faible</option></select><input required name="title" className={`${input} w-full`} placeholder="Titre de l’alerte"/><textarea name="description" className="min-h-24 w-full rounded border p-3 text-[13px]" placeholder="Description"/>{error&&<p className="text-red-600">{error}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className={button}>Annuler</button><button className="rounded bg-[#12c76f] px-4 py-2 text-white">Créer</button></div></form></div>}
function Status({item}:{item:TrackingItem}){return <span className={`rounded-full px-2 py-1 text-[11px] ${item.is_delayed?'bg-red-50 text-red-700':item.risk_level==='HIGH'||item.risk_level==='CRITICAL'?'bg-orange-50 text-orange-700':'bg-emerald-50 text-emerald-700'}`}>{item.status}</span>}
function freshness(value:string){const minutes=(Date.now()-new Date(value).getTime())/60000;return minutes<15?'Temps réel':minutes<180?'Récent':minutes<1440?'Ancien':'Signal perdu'}
function formatDate(value?:string|null){if(!value)return'—';return new Intl.DateTimeFormat('fr-FR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value))}
function message(error:unknown){if(axios.isAxiosError(error))return String(error.response?.data?.detail||error.message);return error instanceof Error?error.message:'Erreur inattendue'}
