import csv,io,json
from fastapi import HTTPException
from sqlalchemy import text
from app.db.database import engine
def rows(r):return [dict(x) for x in r.mappings().all()]
def js(v):return json.dumps(v,default=str)
def audit(c,o,s,e,a,n,old=None,new=None,reason=None):c.execute(text("insert into service_audit_events(org_id,service_id,event_type,old_values,new_values,reason,actor_id,actor_name) values(:o,cast(:s as uuid),:e,cast(:old as jsonb),cast(:new as jsonb),:r,:a,:n)"),{"o":o,"s":s,"e":e,"old":js(old) if old else None,"new":js(new) if new else None,"r":reason,"a":a,"n":n})
def listing(o,q=None,status=None,category=None,mode=None,workspace=None):
 clauses=["s.org_id=:o","s.archived_at is null"];p={"o":o,"q":f"%{q or ''}%","status":status,"category":category,"mode":mode,"workspace":workspace}
 if q:clauses.append("(s.service_name ilike :q or s.service_code ilike :q or s.description ilike :q)")
 if status:clauses.append("s.status=:status")
 if category:clauses.append("s.category=:category")
 if mode:clauses.append("s.shipping_mode=:mode")
 if workspace:clauses.append("(s.workspace_id is null or s.workspace_id=:workspace)")
 with engine.connect() as c:
  items=rows(c.execute(text(f"""select s.*,(select count(*) from service_route_offerings x where x.org_id=s.org_id and x.service_id=s.id)::int route_count,(select min(g.calculation_method) from pricing_grids g where g.org_id=s.org_id and g.shipping_service_id=s.id and g.status='ACTIVE') pricing_method,(select min(g.currency_code) from pricing_grids g where g.org_id=s.org_id and g.shipping_service_id=s.id and g.status='ACTIVE') pricing_currency,(select min(r.amount) from pricing_grid_rules r join pricing_grids g on g.id=r.grid_id where r.org_id=s.org_id and g.shipping_service_id=s.id and g.status='ACTIVE' and r.action_type='SET_PRICE' and r.active) starting_price,(select count(*) from cargo_packages cp where cp.org_id=s.org_id and cp.shipping_service_id=s.id and cp.deleted_at is null)::int package_count,(select round(avg(extract(epoch from (cp.updated_at-cp.created_at))/86400)::numeric,1) from cargo_packages cp where cp.org_id=s.org_id and cp.shipping_service_id=s.id and cp.status='DELIVERED' and cp.deleted_at is null) real_delay_days from shipping_services s where {' and '.join(clauses)} order by s.status='ACTIVE' desc,s.priority,s.service_name"""),p));return {"items":items,"total":len(items)}
def stats(o):
 with engine.connect() as c:return dict(c.execute(text("""select count(*) filter(where status='ACTIVE')::int active,count(*) filter(where shipping_mode='AIR' and status='ACTIVE')::int air,count(*) filter(where shipping_mode='SEA' and status='ACTIVE')::int sea,count(*) filter(where shipping_mode='EXPRESS' and status='ACTIVE')::int express,count(*) filter(where category<>'TRANSPORT' and status='ACTIVE')::int complementary,count(*) filter(where status='SUSPENDED')::int suspended,(select count(*) from cargo_packages p where p.org_id=:o and p.shipping_service_id is not null and date_trunc('month',p.created_at)=date_trunc('month',now()))::int packages_month from shipping_services where org_id=:o and archived_at is null"""),{"o":o}).mappings().one())
def catalog(o):
 with engine.connect() as c:return {"routes":rows(c.execute(text("select id,route_code,route_name,origin_country,origin_city,destination_country,destination_city from shipping_routes where org_id=:o and status in('ACTIVE','LIMITED') order by route_name"),{"o":o})),"warehouses":rows(c.execute(text("select id,warehouse_name name,city,country_code country from warehouses where org_id=:o and active order by warehouse_name"),{"o":o})),"offices":rows(c.execute(text("select id,city||' — '||office_type name,city,country from agency_offices where org_id=:o and is_active order by city"),{"o":o})),"categories":rows(c.execute(text("select id,code,name from pricing_categories where org_id=:o and active order by name"),{"o":o}))}
def create(o,a,n,p):
 with engine.begin() as c:
  row=dict(c.execute(text("""insert into shipping_services(org_id,service_code,service_name,description,workspace_id,category,service_type,shipping_mode,eta_min_days,eta_max_days,volumetric_divisor,minimum_charge_minor,maximum_weight_kg,maximum_volume_cbm,currency_code,priority,status,availability,owner_id,owner_name,public_visible,quote_only,seasonal_from,seasonal_until,minimum_weight_kg,minimum_cbm,minimum_value,maximum_dimensions_cm,maximum_declared_value,cutoff_hours,sla_target_percent,workflow,public_description,metadata,active) values(:o,:service_code,:service_name,:description,:workspace_id,:category,:service_type,:shipping_mode,:eta_min_days,:eta_max_days,:volumetric_divisor,0,:maximum_weight_kg,:maximum_volume_cbm,:currency_code,:priority,'DRAFT','AVAILABLE',:owner_id,:owner_name,:public_visible,:quote_only,:seasonal_from,:seasonal_until,:minimum_weight_kg,:minimum_cbm,:minimum_value,cast(:maximum_dimensions_cm as jsonb),:maximum_declared_value,:cutoff_hours,:sla_target_percent,cast(:workflow as jsonb),:public_description,cast(:metadata as jsonb),false) returning *"""),{"o":o,**p,"maximum_dimensions_cm":js(p.get('maximum_dimensions_cm') or {}),"workflow":js(p.get('workflow') or ['REQUESTED','ACCEPTED','IN_PROGRESS','COMPLETED','CANCELLED']),"metadata":js(p.get('metadata') or {})}).mappings().one());audit(c,o,str(row['id']),'SERVICE_CREATED',a,n,new=row);return row
def detail(o,s):
 with engine.connect() as c:
  item=c.execute(text("select * from shipping_services where org_id=:o and id=cast(:s as uuid)"),{"o":o,"s":s}).mappings().first()
  if not item:raise HTTPException(404,'service_not_found')
  return {**dict(item),"routes":rows(c.execute(text("select x.*,r.route_code,r.route_name,r.origin_country,r.origin_city,r.destination_country,r.destination_city,w.warehouse_name,off.city||' — '||off.office_type office_name from service_route_offerings x join shipping_routes r on r.id=x.route_id left join warehouses w on w.id=x.origin_warehouse_id left join agency_offices off on off.id=x.destination_office_id where x.org_id=:o and x.service_id=:s order by r.route_name"),{"o":o,"s":s})),"pricing":rows(c.execute(text("select id,grid_code,name,currency_code,calculation_method,status,effective_from,effective_until,version from pricing_grids where org_id=:o and shipping_service_id=:s order by status='ACTIVE' desc,version desc"),{"o":o,"s":s})),"conditions":rows(c.execute(text("select * from service_goods_policies where org_id=:o and shipping_service_id=:s order by goods_category"),{"o":o,"s":s})),"options":rows(c.execute(text("select x.*,linked.service_name linked_service_name from service_options x left join shipping_services linked on linked.id=x.option_service_id where x.org_id=:o and x.service_id=:s order by x.mandatory desc,x.name"),{"o":o,"s":s})),"documents":rows(c.execute(text("select * from service_documents where org_id=:o and service_id=:s order by mandatory desc,document_type"),{"o":o,"s":s})),"departures":rows(c.execute(text("select * from cargo_departures where org_id=:o and shipping_service_id=:s order by scheduled_at desc limit 100"),{"o":o,"s":s})),"audit":rows(c.execute(text("select * from service_audit_events where org_id=:o and service_id=:s order by created_at desc limit 100"),{"o":o,"s":s})),"alerts":rows(c.execute(text("select * from service_alerts where org_id=:o and service_id=:s and status='OPEN' order by severity desc"),{"o":o,"s":s}))}
def update(o,s,p,a,n):
 allowed={'service_name','description','workspace_id','category','service_type','shipping_mode','eta_min_days','eta_max_days','volumetric_divisor','maximum_weight_kg','maximum_volume_cbm','currency_code','priority','availability','owner_id','owner_name','public_visible','quote_only','seasonal_from','seasonal_until','minimum_weight_kg','minimum_cbm','minimum_value','maximum_declared_value','cutoff_hours','sla_target_percent','public_description'};values={k:v for k,v in p.items() if k in allowed}
 if not values:raise HTTPException(422,'no_service_changes')
 with engine.begin() as c:
  old=c.execute(text("select * from shipping_services where org_id=:o and id=cast(:s as uuid) for update"),{"o":o,"s":s}).mappings().first()
  if not old:raise HTTPException(404,'service_not_found')
  sets=','.join(f"{k}=:{k}" for k in values);row=dict(c.execute(text(f"update shipping_services set {sets},row_version=row_version+1,updated_at=now() where org_id=:o and id=:s returning *"),{"o":o,"s":s,**values}).mappings().one());audit(c,o,s,'SERVICE_UPDATED',a,n,dict(old),row,p.get('change_reason'));return row
def transition(o,s,status,a,n,reason=None):
 allowed={'DRAFT':{'ACTIVE','ARCHIVED'},'ACTIVE':{'LIMITED','SUSPENDED','INACTIVE','ARCHIVED'},'LIMITED':{'ACTIVE','SUSPENDED','INACTIVE'},'SUSPENDED':{'ACTIVE','INACTIVE','ARCHIVED'},'INACTIVE':{'ACTIVE','ARCHIVED'},'ARCHIVED':set()}
 with engine.begin() as c:
  old=c.execute(text("select * from shipping_services where org_id=:o and id=cast(:s as uuid) for update"),{"o":o,"s":s}).mappings().first()
  if not old:raise HTTPException(404,'service_not_found')
  if status not in allowed.get(old['status'],set()):raise HTTPException(409,'invalid_service_transition')
  row=dict(c.execute(text("update shipping_services set status=:status,active=:active,availability=case when :status='SUSPENDED' then 'SUSPENDED' when :status='LIMITED' then 'LIMITED' when :status='ACTIVE' then 'AVAILABLE' else availability end,archived_at=case when :status='ARCHIVED' then now() else archived_at end,row_version=row_version+1,updated_at=now() where org_id=:o and id=:s returning *"),{"status":status,"active":status in('ACTIVE','LIMITED'),"o":o,"s":s}).mappings().one());audit(c,o,s,'SERVICE_'+status,a,n,dict(old),row,reason);return row
def child(o,s,kind,p,a,n):
 with engine.begin() as c:
  if not c.execute(text("select 1 from shipping_services where org_id=:o and id=cast(:s as uuid)"),{"o":o,"s":s}).first():raise HTTPException(404,'service_not_found')
  if kind=='route':sql="insert into service_route_offerings(org_id,service_id,route_id,workspace_id,origin_warehouse_id,destination_office_id,availability,eta_min_days,eta_max_days,cutoff_hours,capacity_weight_kg,capacity_cbm,effective_from,effective_until,public_visible,metadata) values(:o,:s,cast(:route_id as uuid),:workspace_id,cast(:origin_warehouse_id as uuid),cast(:destination_office_id as uuid),:availability,:eta_min_days,:eta_max_days,:cutoff_hours,:capacity_weight_kg,:capacity_cbm,:effective_from,:effective_until,:public_visible,cast(:metadata as jsonb)) on conflict(service_id,route_id,workspace_id) do update set origin_warehouse_id=excluded.origin_warehouse_id,destination_office_id=excluded.destination_office_id,availability=excluded.availability,eta_min_days=excluded.eta_min_days,eta_max_days=excluded.eta_max_days,cutoff_hours=excluded.cutoff_hours,capacity_weight_kg=excluded.capacity_weight_kg,capacity_cbm=excluded.capacity_cbm,effective_until=excluded.effective_until,public_visible=excluded.public_visible,metadata=excluded.metadata,updated_at=now() returning *";p={**p,'workspace_id':p.get('workspace_id') or 'ORGANIZATION','metadata':js(p.get('metadata') or {})}
  elif kind=='option':sql="insert into service_options(org_id,service_id,option_service_id,option_code,name,description,mandatory,dependency_stage,configuration) values(:o,:s,cast(:option_service_id as uuid),:option_code,:name,:description,:mandatory,:dependency_stage,cast(:configuration as jsonb)) on conflict(service_id,option_code) do update set option_service_id=excluded.option_service_id,name=excluded.name,description=excluded.description,mandatory=excluded.mandatory,dependency_stage=excluded.dependency_stage,configuration=excluded.configuration,active=true returning *";p={**p,'configuration':js(p.get('configuration') or {})}
  elif kind=='document':sql="insert into service_documents(org_id,service_id,route_id,document_type,mandatory,conditions) values(:o,:s,cast(:route_id as uuid),:document_type,:mandatory,cast(:conditions as jsonb)) on conflict(service_id,route_id,document_type) do update set mandatory=excluded.mandatory,conditions=excluded.conditions,active=true returning *";p={**p,'conditions':js(p.get('conditions') or {})}
  elif kind=='condition':sql="insert into service_goods_policies(org_id,shipping_service_id,goods_category,decision,required_documents,handling_instructions) values(:o,:s,:goods_category,:decision,cast(:required_documents as jsonb),:handling_instructions) on conflict(shipping_service_id,goods_category) do update set decision=excluded.decision,required_documents=excluded.required_documents,handling_instructions=excluded.handling_instructions,active=true returning *";p={**p,'required_documents':js(p.get('required_documents') or [])}
  else:raise HTTPException(422,'invalid_service_child')
  row=dict(c.execute(text(sql),{'o':o,'s':s,**p}).mappings().one());audit(c,o,s,kind.upper()+'_CONFIGURED',a,n,new=row);return row
def duplicate(o,s,a,n):
 d=detail(o,s);base=d.copy()
 with engine.begin() as c:
  code=f"{base['service_code']}-COPY-{str(base['id'])[:4]}";row=dict(c.execute(text("""insert into shipping_services(org_id,service_code,service_name,description,workspace_id,category,service_type,shipping_mode,eta_min_days,eta_max_days,volumetric_divisor,maximum_weight_kg,maximum_volume_cbm,currency_code,priority,status,availability,owner_id,owner_name,public_visible,quote_only,minimum_weight_kg,minimum_cbm,minimum_value,maximum_declared_value,cutoff_hours,sla_target_percent,workflow,public_description,metadata,active) select org_id,:code,service_name||' — copie',description,workspace_id,category,service_type,shipping_mode,eta_min_days,eta_max_days,volumetric_divisor,maximum_weight_kg,maximum_volume_cbm,currency_code,priority,'DRAFT','AVAILABLE',owner_id,owner_name,false,quote_only,minimum_weight_kg,minimum_cbm,minimum_value,maximum_declared_value,cutoff_hours,sla_target_percent,workflow,public_description,metadata,false from shipping_services where org_id=:o and id=:s returning *"""),{'o':o,'s':s,'code':code}).mappings().one());audit(c,o,str(row['id']),'SERVICE_DUPLICATED',a,n,new={'source':s});return row
def recommend(o,p):
 with engine.connect() as c:
  items=rows(c.execute(text("""select s.id,s.service_code,s.service_name,s.shipping_mode,s.eta_min_days,s.eta_max_days,s.availability,x.route_id,r.route_name,g.id pricing_grid_id,g.calculation_method,g.currency_code from shipping_services s join service_route_offerings x on x.service_id=s.id and x.org_id=s.org_id join shipping_routes r on r.id=x.route_id and r.org_id=x.org_id left join pricing_grids g on g.org_id=s.org_id and g.shipping_service_id=s.id and g.route_id=x.route_id and g.status='ACTIVE' where s.org_id=:o and s.status in('ACTIVE','LIMITED') and x.availability in('AVAILABLE','LIMITED','QUOTE_ONLY') and lower(r.destination_country)=lower(:destination) and (:origin is null or lower(r.origin_country)=lower(:origin)) and (:mode is null or s.shipping_mode=:mode) and (s.maximum_weight_kg is null or s.maximum_weight_kg>=:weight) and (s.maximum_volume_cbm is null or s.maximum_volume_cbm>=:cbm) and not exists(select 1 from service_goods_policies gp where gp.org_id=s.org_id and gp.shipping_service_id=s.id and lower(gp.goods_category)=lower(:goods) and gp.decision='PROHIBITED') order by x.availability='AVAILABLE' desc,s.eta_max_days,s.priority limit 20"""),{'o':o,'destination':p['destination_country'],'origin':p.get('origin_country'),'mode':p.get('shipping_mode'),'weight':p.get('weight_kg') or 0,'cbm':p.get('volume_cbm') or 0,'goods':p.get('goods_category') or ''}));return {'items':items,'requires_confirmation':True}
def analytics(o):
 with engine.connect() as c:return {'by_service':rows(c.execute(text("""select s.service_name label,count(p.id)::int packages,coalesce(sum(p.weight_kg),0) weight_kg,round(avg(extract(epoch from(p.updated_at-p.created_at))/86400)::numeric,1) average_days from shipping_services s left join cargo_packages p on p.org_id=s.org_id and p.shipping_service_id=s.id and p.deleted_at is null where s.org_id=:o group by s.id order by packages desc"""),{'o':o})),'by_route':rows(c.execute(text("""select s.service_name||' · '||r.route_name label,count(p.id)::int packages from service_route_offerings x join shipping_services s on s.id=x.service_id join shipping_routes r on r.id=x.route_id left join cargo_packages p on p.org_id=x.org_id and p.shipping_service_id=s.id and p.route_id=r.id and p.deleted_at is null where x.org_id=:o group by s.id,r.id order by packages desc limit 30"""),{'o':o}))}
def detect_alerts(o):
 with engine.begin() as c:
  c.execute(text("insert into service_alerts(org_id,service_id,alert_type,severity,message) select s.org_id,s.id,'NO_ROUTE','HIGH','Service actif sans route disponible.' from shipping_services s where s.org_id=:o and s.status='ACTIVE' and not exists(select 1 from service_route_offerings x where x.service_id=s.id and x.org_id=s.org_id and x.availability in('AVAILABLE','LIMITED')) on conflict(service_id,alert_type,status) do nothing"),{'o':o});c.execute(text("insert into service_alerts(org_id,service_id,alert_type,severity,message) select s.org_id,s.id,'NO_PRICING','HIGH','Service actif sans grille tarifaire active.' from shipping_services s where s.org_id=:o and s.status='ACTIVE' and not s.quote_only and not exists(select 1 from pricing_grids g where g.shipping_service_id=s.id and g.org_id=s.org_id and g.status='ACTIVE') on conflict(service_id,alert_type,status) do nothing"),{'o':o});return {'open':c.execute(text("select count(*) from service_alerts where org_id=:o and status='OPEN'"),{'o':o}).scalar_one()}
def export(o):
 out=io.StringIO();w=csv.writer(out);w.writerow(['code','service','category','mode','eta_min','eta_max','routes','pricing','availability','status'])
 for x in listing(o)['items']:w.writerow([x['service_code'],x['service_name'],x['category'],x['shipping_mode'],x['eta_min_days'],x['eta_max_days'],x['route_count'],x['pricing_method'],x['availability'],x['status']])
 return '\ufeff'+out.getvalue()
