import json
from decimal import Decimal,ROUND_HALF_UP
from fastapi import HTTPException
from sqlalchemy import text
from app.db.database import engine
def rows(r):return [dict(x) for x in r.mappings().all()]
def event(c,o,t,a,n,route=None,service=None,p=None):c.execute(text("insert into route_service_events(org_id,route_id,shipping_service_id,event_type,actor_id,actor_name,payload) values(:o,cast(:r as uuid),cast(:s as uuid),:t,:a,:n,cast(:p as jsonb))"),{"o":o,"r":route,"s":service,"t":t,"a":a,"n":n,"p":json.dumps(p or {},default=str)})
def list_all(o):
 with engine.connect() as c:return {"routes":rows(c.execute(text("select r.*,(select count(*) from shipping_services s where s.route_id=r.id and s.org_id=r.org_id and s.active)::int service_count from shipping_routes r where r.org_id=:o and r.archived_at is null order by r.active desc,r.created_at desc"),{"o":o})),"services":rows(c.execute(text("select s.*,r.route_name,r.route_code,(select count(*) from pricing_components p where p.shipping_service_id=s.id and p.org_id=s.org_id and p.active and p.effective_from<=now() and (p.effective_until is null or p.effective_until>now()))::int pricing_count from shipping_services s left join shipping_routes r on r.id=s.route_id and r.org_id=s.org_id where s.org_id=:o order by s.active desc,s.priority"),{"o":o}))}
def create_route(o,a,n,p):
 with engine.begin() as c:
  row=dict(c.execute(text("insert into shipping_routes(org_id,route_code,route_name,origin_country,origin_city,destination_country,destination_city,transport_mode,eta_min_days,eta_max_days,expected_duration_days,timezone,metadata) values(:o,:route_code,:route_name,:origin_country,:origin_city,:destination_country,:destination_city,:transport_mode,:eta_min_days,:eta_max_days,:eta_max_days,:timezone,cast(:metadata as jsonb)) returning *"),{"o":o,**p,"metadata":json.dumps(p.get('metadata') or {})}).mappings().one());event(c,o,'ROUTE_CREATED',a,n,str(row['id']),p={"code":p['route_code']});return row
def create_service(o,a,n,p):
 with engine.begin() as c:
  if not c.execute(text("select 1 from shipping_routes where id=cast(:r as uuid) and org_id=:o and archived_at is null"),{"r":p['route_id'],"o":o}).first():raise HTTPException(422,'route_not_found')
  row=dict(c.execute(text("insert into shipping_services(org_id,route_id,service_code,service_name,shipping_mode,service_type,eta_min_days,eta_max_days,volumetric_divisor,minimum_charge_minor,maximum_weight_kg,maximum_volume_cbm,currency_code,priority,metadata) values(:o,cast(:route_id as uuid),:service_code,:service_name,:shipping_mode,:service_type,:eta_min_days,:eta_max_days,:volumetric_divisor,:minimum_charge_minor,:maximum_weight_kg,:maximum_volume_cbm,:currency_code,:priority,cast(:metadata as jsonb)) returning *"),{"o":o,**p,"metadata":json.dumps(p.get('metadata') or {})}).mappings().one());event(c,o,'SERVICE_CREATED',a,n,p['route_id'],str(row['id']));return row
def add_component(o,a,n,service,p):
 with engine.begin() as c:
  if not c.execute(text("select 1 from shipping_services where id=cast(:s as uuid) and org_id=:o"),{"s":service,"o":o}).first():raise HTTPException(422,'service_not_found')
  c.execute(text("update pricing_components set effective_until=coalesce(effective_until,now()),active=false where org_id=:o and shipping_service_id=:s and component_code=:code and active"),{"o":o,"s":service,"code":p['component_code']});version=c.execute(text("select coalesce(max(version_number),0)+1 from pricing_components where org_id=:o and shipping_service_id=:s and component_code=:code"),{"o":o,"s":service,"code":p['component_code']}).scalar_one();row=dict(c.execute(text("insert into pricing_components(org_id,shipping_service_id,component_code,component_name,calculation_type,amount_minor,percentage,currency_code,priority,min_quantity,max_quantity,effective_from,effective_until,version_number,metadata) values(:o,cast(:s as uuid),:component_code,:component_name,:calculation_type,:amount_minor,:percentage,:currency_code,:priority,:min_quantity,:max_quantity,:effective_from,:effective_until,:version,cast(:metadata as jsonb)) returning *"),{"o":o,"s":service,"version":version,**p,"metadata":json.dumps(p.get('metadata') or {})}).mappings().one());event(c,o,'PRICE_VERSION_CREATED',a,n,service=service,p={"component":p['component_code'],"version":version});return row
def simulate(o,service,weight,volume,declared=0):
 with engine.connect() as c:
  s=c.execute(text("select * from shipping_services where id=:s and org_id=:o and active"),{"s":service,"o":o}).mappings().first()
  if not s:raise HTTPException(404,'service_not_found')
  components=rows(c.execute(text("select * from pricing_components where org_id=:o and shipping_service_id=:s and active and effective_from<=now() and (effective_until is null or effective_until>now()) order by priority,created_at"),{"o":o,"s":service}))
  volumetric=Decimal(str(volume or 0))*Decimal('1000000')/Decimal(str(s.get('volumetric_divisor') or 6000));chargeable=max(Decimal(str(weight or 0)),volumetric);total=Decimal('0');breakdown=[]
  for x in components:
   typ=x['calculation_type'];qty=chargeable if typ=='PER_KG' else Decimal(str(volume or 0)) if typ=='PER_CBM' else Decimal('1');line=Decimal(str(x.get('amount_minor') or 0))*qty if typ in ('PER_KG','PER_CBM','FIXED') else total*Decimal(str(x.get('percentage') or 0))/100 if typ=='PERCENTAGE' else Decimal('0');line=line.quantize(Decimal('1'),rounding=ROUND_HALF_UP);total+=line;breakdown.append({"code":x['component_code'],"type":typ,"quantity":float(qty),"line_total_minor":int(line),"version":x['version_number']})
  total=max(total,Decimal(str(s.get('minimum_charge_minor') or 0)));return {"service_id":service,"currency":s['currency_code'],"actual_weight_kg":weight,"volumetric_weight_kg":float(volumetric.quantize(Decimal('.001'))),"chargeable_weight_kg":float(chargeable),"total_minor":int(total),"breakdown":breakdown,"eta":{"min_days":s['eta_min_days'],"max_days":s['eta_max_days']}}
