import json,hashlib
from decimal import Decimal,ROUND_HALF_UP
from fastapi import HTTPException
from sqlalchemy import text
from app.db.database import engine
def rows(r):return [dict(x) for x in r.mappings().all()]
def event(c,o,t,a,n,route=None,service=None,p=None):c.execute(text("insert into route_service_events(org_id,route_id,shipping_service_id,event_type,actor_id,actor_name,payload) values(:o,cast(:r as uuid),cast(:s as uuid),:t,:a,:n,cast(:p as jsonb))"),{"o":o,"r":route,"s":service,"t":t,"a":a,"n":n,"p":json.dumps(p or {},default=str)})
def list_all(o):
 with engine.connect() as c:return {"routes":rows(c.execute(text("select r.*,(select count(*) from shipping_services s where s.route_id=r.id and s.org_id=r.org_id and s.active)::int service_count from shipping_routes r where r.org_id=:o and r.archived_at is null order by r.active desc,r.created_at desc"),{"o":o})),"services":rows(c.execute(text("select s.*,r.route_name,r.route_code,(select count(*) from pricing_components p where p.shipping_service_id=s.id and p.org_id=s.org_id and p.active and p.effective_from<=now() and (p.effective_until is null or p.effective_until>now()))::int pricing_count from shipping_services s left join shipping_routes r on r.id=s.route_id and r.org_id=s.org_id where s.org_id=:o order by s.active desc,s.priority"),{"o":o}))}
def create_route(o,a,n,p):
 with engine.begin() as c:
  row=dict(c.execute(text("insert into shipping_routes(org_id,route_code,route_name,origin_country,origin_city,destination_country,destination_city,transport_mode,eta_min_days,eta_max_days,expected_duration_days,timezone,metadata) values(:o,:route_code,:route_name,:origin_country,:origin_city,:destination_country,:destination_city,:transport_mode,:eta_min_days,:eta_max_days,:eta_max_days,:timezone,cast(:metadata as jsonb)) returning *"),{"o":o,**p,"metadata":json.dumps(p.get('metadata') or {})}).mappings().one());event(c,o,'ROUTE_CREATED',a,n,str(row['id']),p={"code":p['route_code']});return row
def create_service(o,a,n,p):
 with engine.begin() as c:
  if not c.execute(text("select 1 from shipping_routes where id=cast(:r as uuid) and org_id=:o and archived_at is null"),{"r":p['route_id'],"o":o}).first():raise HTTPException(422,'route_not_found')
  row=dict(c.execute(text("insert into shipping_services(org_id,route_id,service_code,service_name,shipping_mode,service_type,eta_min_days,eta_max_days,volumetric_divisor,minimum_charge_minor,maximum_weight_kg,maximum_volume_cbm,currency_code,priority,metadata) values(:o,cast(:route_id as uuid),:service_code,:service_name,:shipping_mode,:service_type,:eta_min_days,:eta_max_days,:volumetric_divisor,:minimum_charge_minor,:maximum_weight_kg,:maximum_volume_cbm,:currency_code,:priority,cast(:metadata as jsonb)) returning *"),{"o":o,**p,"metadata":json.dumps(p.get('metadata') or {})}).mappings().one());event(c,o,'SERVICE_CREATED',a,n,p['route_id'],str(row['id']));return row
def add_component(o,a,n,service,p):
 with engine.begin() as c:
  if not c.execute(text("select 1 from shipping_services where id=cast(:s as uuid) and org_id=:o"),{"s":service,"o":o}).first():raise HTTPException(422,'service_not_found')
  c.execute(text("update pricing_components set effective_until=coalesce(effective_until,now()),active=false where org_id=:o and shipping_service_id=:s and component_code=:code and active"),{"o":o,"s":service,"code":p['component_code']});version=c.execute(text("select coalesce(max(version_number),0)+1 from pricing_components where org_id=:o and shipping_service_id=:s and component_code=:code"),{"o":o,"s":service,"code":p['component_code']}).scalar_one();row=dict(c.execute(text("insert into pricing_components(org_id,shipping_service_id,component_code,component_name,calculation_type,amount_minor,percentage,currency_code,priority,min_quantity,max_quantity,effective_from,effective_until,version_number,metadata) values(:o,cast(:s as uuid),:component_code,:component_name,:calculation_type,:amount_minor,:percentage,:currency_code,:priority,:min_quantity,:max_quantity,:effective_from,:effective_until,:version,cast(:metadata as jsonb)) returning *"),{"o":o,"s":service,"version":version,**p,"metadata":json.dumps(p.get('metadata') or {})}).mappings().one());event(c,o,'PRICE_VERSION_CREATED',a,n,service=service,p={"component":p['component_code'],"version":version});return row
def service_configuration(o,service):
 with engine.connect() as c:return {"stops":rows(c.execute(text("select rs.* from route_stops rs join shipping_services s on s.route_id=rs.route_id and s.org_id=rs.org_id where s.id=:s and s.org_id=:o order by rs.position"),{"s":service,"o":o})),"departures":rows(c.execute(text("select * from service_departure_rules where shipping_service_id=:s and org_id=:o order by weekday"),{"s":service,"o":o})),"policies":rows(c.execute(text("select * from service_goods_policies where shipping_service_id=:s and org_id=:o"),{"s":service,"o":o})),"adjustments":rows(c.execute(text("select * from service_price_adjustments where shipping_service_id=:s and org_id=:o order by priority"),{"s":service,"o":o}))}
def configure(o,a,n,service,kind,p):
 with engine.begin() as c:
  s=c.execute(text("select * from shipping_services where id=:s and org_id=:o"),{"s":service,"o":o}).mappings().first()
  if not s:raise HTTPException(404,'service_not_found')
  if kind=='stop':sql="insert into route_stops(org_id,route_id,position,country_code,city,location_name,stop_type,planned_duration_hours) values(:o,:route_id,:position,:country_code,:city,:location_name,:stop_type,:planned_duration_hours) on conflict(route_id,position) do update set country_code=excluded.country_code,city=excluded.city,location_name=excluded.location_name,stop_type=excluded.stop_type,planned_duration_hours=excluded.planned_duration_hours returning *";p={**p,"route_id":s['route_id']}
  elif kind=='departure':sql="insert into service_departure_rules(org_id,shipping_service_id,weekday,cutoff_time,departure_time,capacity_weight_kg,capacity_cbm,active) values(:o,:service_id,:weekday,:cutoff_time,:departure_time,:capacity_weight_kg,:capacity_cbm,true) on conflict(shipping_service_id,weekday) do update set cutoff_time=excluded.cutoff_time,departure_time=excluded.departure_time,capacity_weight_kg=excluded.capacity_weight_kg,capacity_cbm=excluded.capacity_cbm,active=true returning *"
  elif kind=='policy':sql="insert into service_goods_policies(org_id,shipping_service_id,goods_category,decision,required_documents,handling_instructions) values(:o,:service_id,:goods_category,:decision,cast(:required_documents as jsonb),:handling_instructions) on conflict(shipping_service_id,goods_category) do update set decision=excluded.decision,required_documents=excluded.required_documents,handling_instructions=excluded.handling_instructions,active=true returning *";p={**p,"required_documents":json.dumps(p.get('required_documents') or [])}
  elif kind=='adjustment':sql="insert into service_price_adjustments(org_id,shipping_service_id,adjustment_code,adjustment_name,adjustment_type,amount_minor,percentage,client_id,goods_category,min_weight_kg,effective_from,effective_until,priority) values(:o,:service_id,:adjustment_code,:adjustment_name,:adjustment_type,:amount_minor,:percentage,cast(:client_id as uuid),:goods_category,:min_weight_kg,:effective_from,:effective_until,:priority) returning *"
  else:raise HTTPException(422,'invalid_configuration_kind')
  row=dict(c.execute(text(sql),{"o":o,"service_id":service,**p}).mappings().one());event(c,o,kind.upper()+'_CONFIGURED',a,n,service=service,p=row);return row
def simulate(o,service,weight,volume,declared=0,client_id=None,goods_category=None,actor=None):
 with engine.begin() as c:
  s=c.execute(text("select * from shipping_services where id=:s and org_id=:o and active"),{"s":service,"o":o}).mappings().first()
  if not s:raise HTTPException(404,'service_not_found')
  if s.get('maximum_weight_kg') and Decimal(str(weight or 0))>s['maximum_weight_kg']:raise HTTPException(422,'service_weight_capacity_exceeded')
  if s.get('maximum_volume_cbm') and Decimal(str(volume or 0))>s['maximum_volume_cbm']:raise HTTPException(422,'service_volume_capacity_exceeded')
  policy=c.execute(text("select * from service_goods_policies where org_id=:o and shipping_service_id=:s and active and lower(goods_category)=lower(:g)"),{"o":o,"s":service,"g":goods_category or ''}).mappings().first()
  if policy and policy['decision']=='PROHIBITED':raise HTTPException(422,'goods_prohibited_for_service')
  components=rows(c.execute(text("select * from pricing_components where org_id=:o and shipping_service_id=:s and active and effective_from<=now() and (effective_until is null or effective_until>now()) order by priority,created_at"),{"o":o,"s":service}));volumetric=Decimal(str(volume or 0))*Decimal('1000000')/Decimal(str(s.get('volumetric_divisor') or 6000));chargeable=max(Decimal(str(weight or 0)),volumetric);total=Decimal('0');breakdown=[]
  for x in components:
   typ=x['calculation_type'];qty=chargeable if typ=='PER_KG' else Decimal(str(volume or 0)) if typ=='PER_CBM' else Decimal('1');line=Decimal(str(x.get('amount_minor') or 0))*qty if typ in ('PER_KG','PER_CBM','FIXED') else total*Decimal(str(x.get('percentage') or 0))/100 if typ=='PERCENTAGE' else Decimal('0');line=line.quantize(Decimal('1'),rounding=ROUND_HALF_UP);total+=line;breakdown.append({"code":x['component_code'],"type":typ,"quantity":float(qty),"line_total_minor":int(line),"version":x['version_number']})
  adjustments=rows(c.execute(text("select * from service_price_adjustments where org_id=:o and shipping_service_id=:s and active and effective_from<=now() and (effective_until is null or effective_until>now()) and (client_id is null or client_id=cast(:client as uuid)) and (goods_category is null or lower(goods_category)=lower(:goods)) order by priority"),{"o":o,"s":service,"client":client_id,"goods":goods_category}))
  for x in adjustments:
   line=Decimal(str(x.get('amount_minor') or 0)) if x['adjustment_type']=='FIXED' else total*Decimal(str(x.get('percentage') or 0))/100;line=line.quantize(Decimal('1'));total+=line;breakdown.append({"code":x['adjustment_code'],"type":x['adjustment_type'],"line_total_minor":int(line),"adjustment":True})
  total=max(total,Decimal(str(s.get('minimum_charge_minor') or 0)));fingerprint=hashlib.sha256(json.dumps(breakdown,sort_keys=True).encode()).hexdigest();result={"service_id":service,"currency":s['currency_code'],"chargeable_weight_kg":float(chargeable),"total_minor":int(total),"breakdown":breakdown,"eta":{"min_days":s['eta_min_days'],"max_days":s['eta_max_days']},"restriction":{"decision":policy['decision'] if policy else 'ALLOWED',"required_documents":policy['required_documents'] if policy else []},"pricing_fingerprint":fingerprint};c.execute(text("insert into pricing_simulation_snapshots(org_id,shipping_service_id,client_id,input_payload,result_payload,pricing_version_fingerprint,created_by) values(:o,:s,cast(:client as uuid),cast(:input as jsonb),cast(:result as jsonb),:fp,:actor)"),{"o":o,"s":service,"client":client_id,"input":json.dumps({"weight":weight,"volume":volume,"declared":declared,"goods_category":goods_category}),"result":json.dumps(result),"fp":fingerprint,"actor":actor});return result
