alter table shipping_routes add column if not exists origin_type text default 'CITY';
alter table shipping_routes add column if not exists destination_type text default 'CITY';
alter table shipping_routes add column if not exists eta_min_days integer;
alter table shipping_routes add column if not exists eta_max_days integer;
alter table shipping_routes add column if not exists timezone text;
alter table shipping_routes add column if not exists row_version integer not null default 1;
alter table shipping_routes add column if not exists archived_at timestamptz;
alter table shipping_routes add column if not exists metadata jsonb not null default '{}';
alter table shipping_services add column if not exists route_id uuid references shipping_routes(id);
alter table shipping_services add column if not exists service_type text default 'STANDARD';
alter table shipping_services add column if not exists volumetric_divisor numeric(12,3);
alter table shipping_services add column if not exists minimum_charge_minor bigint not null default 0;
alter table shipping_services add column if not exists maximum_weight_kg numeric(18,3);
alter table shipping_services add column if not exists maximum_volume_cbm numeric(18,4);
alter table shipping_services add column if not exists currency_code text not null default 'USD';
alter table shipping_services add column if not exists row_version integer not null default 1;
alter table pricing_components add column if not exists min_quantity numeric(18,4);
alter table pricing_components add column if not exists max_quantity numeric(18,4);
alter table pricing_components add column if not exists effective_from timestamptz not null default now();
alter table pricing_components add column if not exists effective_until timestamptz;
alter table pricing_components add column if not exists version_number integer not null default 1;
alter table pricing_components add column if not exists row_version integer not null default 1;
create table if not exists route_stops(id uuid primary key default gen_random_uuid(),org_id text not null references organizations(id),route_id uuid not null references shipping_routes(id) on delete cascade,position integer not null,country_code text,city text,location_name text,stop_type text not null default 'HUB',planned_duration_hours integer not null default 0,unique(route_id,position));
create table if not exists service_departure_rules(id uuid primary key default gen_random_uuid(),org_id text not null references organizations(id),shipping_service_id uuid not null references shipping_services(id) on delete cascade,weekday integer not null check(weekday between 1 and 7),cutoff_time time,departure_time time,capacity_weight_kg numeric(18,3),capacity_cbm numeric(18,4),active boolean not null default true,unique(shipping_service_id,weekday));
create table if not exists route_service_events(id bigserial primary key,org_id text not null references organizations(id),route_id uuid,shipping_service_id uuid,event_type text not null,actor_id text,actor_name text,payload jsonb not null default '{}',created_at timestamptz not null default now());
create index if not exists idx_shipping_routes_tenant on shipping_routes(org_id,active,created_at desc);create index if not exists idx_shipping_services_route on shipping_services(org_id,route_id,active);create index if not exists idx_pricing_components_effective on pricing_components(org_id,shipping_service_id,effective_from,effective_until);
insert into permissions(permission_code,description) values ('routes.read','Consulter routes, services et tarifs'),('routes.manage','Gérer routes et escales'),('services.manage','Gérer les services cargo'),('pricing.manage','Versionner les composants tarifaires'),('pricing.simulate','Simuler un prix auditable') on conflict(permission_code) do update set description=excluded.description;
insert into role_permissions(role_id,permission_id) select r.id,p.id from organization_roles r cross join permissions p where (r.role_code in ('OWNER','MANAGER') and p.permission_code in ('routes.read','routes.manage','services.manage','pricing.manage','pricing.simulate')) or (r.role_code in ('OPERATOR','FINANCE','SUPPORT') and p.permission_code in ('routes.read','pricing.simulate')) on conflict do nothing;
