alter table cargo_departures add column if not exists workspace_id text;
alter table cargo_departures add column if not exists warehouse_id uuid;
alter table cargo_departures add column if not exists destination_office text;
alter table cargo_departures add column if not exists responsible_id text;
alter table cargo_departures add column if not exists responsible_name text;
alter table cargo_departures add column if not exists timezone text not null default 'UTC';
alter table cargo_departures add column if not exists capacity_packages integer;
alter table cargo_departures add column if not exists reserved_packages integer not null default 0;
alter table cargo_departures add column if not exists carrier_type text;
alter table cargo_departures add column if not exists flight_number text;
alter table cargo_departures add column if not exists vessel_name text;
alter table cargo_departures add column if not exists voyage_number text;
alter table cargo_departures add column if not exists container_number text;
alter table cargo_departures add column if not exists awb_number text;
alter table cargo_departures add column if not exists bl_number text;
alter table cargo_departures add column if not exists batch_reference text;
alter table cargo_departures add column if not exists published boolean not null default false;
alter table cargo_departures add column if not exists actual_departure_at timestamptz;
alter table cargo_departures add column if not exists actual_arrival_at timestamptz;
alter table cargo_departures add column if not exists delay_reason text;
alter table cargo_departures add column if not exists checklist jsonb not null default '{"packages":false,"weight":false,"documents":false,"manifest":false,"payments":false,"carrier":false,"final_approval":false}'::jsonb;
alter table cargo_departures drop constraint if exists cargo_departures_status_check;
alter table cargo_departures add constraint cargo_departures_status_check check(status in ('DRAFT','OPEN','PLANNED','PENDING_CONFIRMATION','CONFIRMED','CLOSED','LOADING','READY_TO_DEPART','DEPARTED','DELAYED','CANCELLED','ARRIVED','COMPLETED'));
create index if not exists idx_departures_org_cutoff on cargo_departures(org_id,cutoff_at) where status not in ('CANCELLED','COMPLETED','ARRIVED');
create index if not exists idx_departures_org_route on cargo_departures(org_id,shipping_service_id,scheduled_at);
insert into permissions(permission_code,description) values ('departures.notify','Notifier les clients concernés'),('departures.export','Exporter le calendrier'),('departures.override_capacity','Autoriser un dépassement de capacité') on conflict(permission_code) do update set description=excluded.description;
insert into role_permissions(role_id,permission_id) select r.id,p.id from organization_roles r cross join permissions p where r.role_code in ('OWNER','MANAGER') and p.permission_code in ('departures.notify','departures.export','departures.override_capacity') on conflict do nothing;
