alter table cargo_departures add column if not exists workspace_id text;
alter table cargo_departures add column if not exists warehouse_id uuid;
alter table cargo_departures add column if not exists destination_office text;
alter table cargo_departures add column if not exists responsible_id text;
alter table cargo_departures add column if not exists responsible_name text;
alter table cargo_departures add column if not exists timezone text not null default 'UTC';
alter table cargo_departures add column if not exists capacity_packages integer;
alter table cargo_departures add column if not exists reserved_packages integer not null default 0;
alter table cargo_departures add column if not exists carrier_type text;
alter table cargo_departures add column if not exists flight_number text;
alter table cargo_departures add column if not exists vessel_name text;
alter table cargo_departures add column if not exists voyage_number text;
alter table cargo_departures add column if not exists container_number text;
alter table cargo_departures add column if not exists awb_number text;
alter table cargo_departures add column if not exists bl_number text;
alter table cargo_departures add column if not exists batch_reference text;
alter table cargo_departures add column if not exists published boolean not null default false;
alter table cargo_departures add column if not exists actual_departure_at timestamptz;
alter table cargo_departures add column if not exists actual_arrival_at timestamptz;
alter table cargo_departures add column if not exists delay_reason text;
alter table cargo_departures add column if not exists checklist jsonb not null default '{"packages":false,"weight":false,"documents":false,"manifest":false,"payments":false,"carrier":false,"final_approval":false}'::jsonb;
alter table cargo_departures drop constraint if exists cargo_departures_status_check;
alter table cargo_departures add constraint cargo_departures_status_check check(status in ('DRAFT','OPEN','PLANNED','PENDING_CONFIRMATION','CONFIRMED','CLOSED','LOADING','READY_TO_DEPART','DEPARTED','DELAYED','CANCELLED','ARRIVED','COMPLETED'));
create index if not exists idx_departures_org_cutoff on cargo_departures(org_id,cutoff_at) where status not in ('CANCELLED','COMPLETED','ARRIVED');
create index if not exists idx_departures_org_route on cargo_departures(org_id,shipping_service_id,scheduled_at);
create table if not exists departure_package_allocations(id uuid primary key default gen_random_uuid(),org_id text not null references organizations(id),departure_id uuid not null references cargo_departures(id) on delete cascade,package_id uuid not null references cargo_packages(id),status text not null default 'PLANNED' check(status in ('PLANNED','LOADED','REMOVED','WAITLISTED')),weight_kg numeric(18,3) not null default 0,volume_cbm numeric(18,4) not null default 0,idempotency_key text not null,created_by text,created_at timestamptz not null default now(),unique(org_id,idempotency_key),unique(departure_id,package_id));
create table if not exists departure_templates(id uuid primary key default gen_random_uuid(),org_id text not null references organizations(id),template_name text not null,shipping_service_id uuid not null references shipping_services(id),timezone text not null default 'UTC',capacity_weight_kg numeric(18,3),capacity_cbm numeric(18,4),capacity_packages integer,checklist jsonb not null default '{}'::jsonb,active boolean not null default true,created_by text,created_at timestamptz not null default now());
create table if not exists departure_recurrences(id uuid primary key default gen_random_uuid(),org_id text not null references organizations(id),template_id uuid references departure_templates(id),shipping_service_id uuid not null references shipping_services(id),frequency text not null check(frequency in ('DAILY','WEEKLY','MONTHLY')),weekdays integer[] not null default '{}',local_time time not null,timezone text not null,cutoff_hours integer not null default 24,horizon_days integer not null default 60,active boolean not null default true,next_generation_at timestamptz,created_by text,created_at timestamptz not null default now());
create table if not exists departure_documents(id uuid primary key default gen_random_uuid(),org_id text not null references organizations(id),departure_id uuid not null references cargo_departures(id) on delete cascade,document_type text not null,file_name text not null,object_path text,mime_type text,size_bytes bigint not null default 0,created_by text,created_at timestamptz not null default now());
create index if not exists idx_departure_packages on departure_package_allocations(org_id,departure_id,status);
insert into permissions(permission_code,description) values ('departures.notify','Notifier les clients concernés'),('departures.export','Exporter le calendrier'),('departures.override_capacity','Autoriser un dépassement de capacité'),('departures.checklist','Valider la checklist avant départ'),('departures.templates','Gérer les modèles et récurrences') on conflict(permission_code) do update set description=excluded.description;
insert into role_permissions(role_id,permission_id) select r.id,p.id from organization_roles r cross join permissions p where (r.role_code in ('OWNER','MANAGER') and p.permission_code in ('departures.notify','departures.export','departures.override_capacity','departures.checklist','departures.templates')) or (r.role_code in ('OPERATOR','WAREHOUSE') and p.permission_code='departures.checklist') on conflict do nothing;
